CREATE SCHEMA "public";
CREATE TABLE "addresses" (
	"id" uuid DEFAULT uuid_generate_v4(),
	"user_id" uuid NOT NULL,
	"address_line" text NOT NULL,
	"city" varchar(255) NOT NULL,
	"district" varchar(255) NOT NULL,
	"ward" varchar(255) NOT NULL,
	"is_default" boolean DEFAULT false NOT NULL,
	CONSTRAINT "address_pkey" PRIMARY KEY("id")
);
CREATE TABLE "cart_item" (
	"user_id" uuid NOT NULL UNIQUE,
	"product_id" uuid NOT NULL UNIQUE,
	"quantity" integer DEFAULT 1 NOT NULL,
	"created_at" timestamp DEFAULT CURRENT_TIMESTAMP,
	"id" uuid PRIMARY KEY DEFAULT uuid_generate_v4(),
	CONSTRAINT "cart_item_user_product_unique" UNIQUE("user_id","product_id"),
	CONSTRAINT "uk2dhdhp9i9ld88nv1bejg9hbx7" UNIQUE("user_id","product_id"),
	CONSTRAINT "cart_item_quantity_check" CHECK ((quantity > 0))
);
CREATE TABLE "category" (
	"id" uuid PRIMARY KEY DEFAULT uuid_generate_v4(),
	"name" varchar(255) NOT NULL CONSTRAINT "category_name_key" UNIQUE,
	"created_at" timestamp DEFAULT CURRENT_TIMESTAMP
);
CREATE TABLE "coupons" (
	"id" uuid PRIMARY KEY DEFAULT uuid_generate_v4(),
	"code" varchar(50) NOT NULL CONSTRAINT "coupons_code_unique" UNIQUE,
	"discount_value" numeric(19, 2) NOT NULL,
	"expiry_date" timestamp,
	"min_order_value" numeric(19, 2) DEFAULT '0' NOT NULL,
	"max_discount" numeric(19, 2),
	"discount_type" varchar(20) NOT NULL,
	"start_date" timestamp,
	"usage_per_user" integer DEFAULT 1 NOT NULL,
	"status" varchar(20) DEFAULT 'ACTIVE' NOT NULL,
	"created_at" timestamp DEFAULT CURRENT_TIMESTAMP,
	"coupon_scope" varchar(255) NOT NULL,
	CONSTRAINT "coupons_discount_type_check" CHECK (((discount_type)::text = ANY ((ARRAY['FIXED'::character varying, 'PERCENT'::character varying])::text[]))),
	CONSTRAINT "coupons_scope_check" CHECK (((coupon_scope)::text = ANY ((ARRAY['ORDER'::character varying, 'SHIPPING'::character varying])::text[]))),
	CONSTRAINT "coupons_status_check" CHECK (((status)::text = ANY ((ARRAY['ACTIVE'::character varying, 'INACTIVE'::character varying])::text[])))
);
CREATE TABLE "inventory" (
	"product_id" uuid PRIMARY KEY,
	"quantity" integer NOT NULL
);
CREATE TABLE "order_coupons" (
	"order_coupon_id" uuid PRIMARY KEY DEFAULT uuid_generate_v4(),
	"order_id" uuid NOT NULL,
	"coupon_id" uuid NOT NULL
);
CREATE TABLE "order_items" (
	"id" uuid PRIMARY KEY DEFAULT uuid_generate_v4(),
	"order_id" uuid NOT NULL,
	"product_id" uuid NOT NULL,
	"quantity" integer NOT NULL,
	"price" numeric(19, 2) NOT NULL
);
CREATE TABLE "order_payments" (
	"id" uuid DEFAULT uuid_generate_v4(),
	"order_id" uuid NOT NULL CONSTRAINT "payments_order_id_unique" UNIQUE,
	"method" integer NOT NULL,
	"status" varchar(50) DEFAULT 'PENDING',
	"paid_at" timestamp,
	"payment_method_id" uuid,
	CONSTRAINT "payments_pkey" PRIMARY KEY("id")
);
CREATE TABLE "orders" (
	"id" uuid PRIMARY KEY DEFAULT uuid_generate_v4(),
	"user_id" uuid NOT NULL,
	"address_id" uuid NOT NULL,
	"subtotal" numeric(19, 2) NOT NULL,
	"discount" numeric(19, 2),
	"shipping_fee" numeric(19, 2),
	"final_price" numeric(19, 2) NOT NULL,
	"status" varchar(50) DEFAULT 'PENDING',
	"created_at" timestamp DEFAULT CURRENT_TIMESTAMP,
	"shipping_method_id" uuid
);
CREATE TABLE "payment_methods" (
	"id" uuid PRIMARY KEY DEFAULT uuid_generate_v4(),
	"code" varchar(50) NOT NULL CONSTRAINT "payment_methods_code_key" UNIQUE,
	"name" varchar(255) NOT NULL,
	"is_active" boolean DEFAULT true,
	"created_at" timestamp DEFAULT CURRENT_TIMESTAMP
);
CREATE TABLE "product" (
	"id" uuid PRIMARY KEY DEFAULT uuid_generate_v4(),
	"name" varchar(255) NOT NULL,
	"price" numeric(12, 2) NOT NULL,
	"description" text,
	"status" varchar(255) DEFAULT 'ACTIVE',
	"created_at" timestamp DEFAULT CURRENT_TIMESTAMP,
	"category_id" uuid,
	"slug" varchar(255) CONSTRAINT "product_slug_key" UNIQUE,
	"is_featured" boolean DEFAULT false
);
CREATE TABLE "product_image" (
	"id" uuid PRIMARY KEY DEFAULT uuid_generate_v4(),
	"product_id" uuid NOT NULL,
	"image_url" text NOT NULL,
	"sort_order" integer DEFAULT 0,
	"created_at" timestamp DEFAULT CURRENT_TIMESTAMP,
	"is_thumbnail" boolean DEFAULT false
);
CREATE TABLE "shipping_methods" (
	"id" uuid PRIMARY KEY DEFAULT uuid_generate_v4(),
	"code" varchar(50) NOT NULL CONSTRAINT "shipping_methods_code_key" UNIQUE,
	"name" varchar(255) NOT NULL,
	"description" text,
	"base_fee" numeric(19, 2) DEFAULT '0' NOT NULL,
	"estimated_days_min" integer,
	"estimated_days_max" integer,
	"is_active" boolean DEFAULT true,
	"created_at" timestamp DEFAULT CURRENT_TIMESTAMP
);
CREATE TABLE "test" (
	"id" bigint PRIMARY KEY GENERATED BY DEFAULT AS IDENTITY (sequence name "test_id_seq" INCREMENT BY 1 MINVALUE 1 MAXVALUE 9223372036854775807 START WITH 1 CACHE 1),
	"name" varchar(255)
);
CREATE TABLE "users" (
	"id" uuid PRIMARY KEY DEFAULT uuid_generate_v4(),
	"email" varchar(255) NOT NULL CONSTRAINT "users_email_unique" UNIQUE,
	"hash_password" varchar(255) NOT NULL,
	"phone" varchar(20),
	"created_at" timestamp DEFAULT CURRENT_TIMESTAMP,
	"full_name" varchar(255)
);
CREATE UNIQUE INDEX "address_pkey" ON "addresses" ("id");
CREATE UNIQUE INDEX "cart_item_pkey" ON "cart_item" ("id");
CREATE INDEX "cart_item_product_id_index" ON "cart_item" ("product_id");
CREATE INDEX "cart_item_user_id_index" ON "cart_item" ("user_id");
CREATE UNIQUE INDEX "cart_item_user_product_unique" ON "cart_item" ("user_id","product_id");
CREATE UNIQUE INDEX "uk2dhdhp9i9ld88nv1bejg9hbx7" ON "cart_item" ("user_id","product_id");
CREATE UNIQUE INDEX "category_name_key" ON "category" ("name");
CREATE UNIQUE INDEX "category_pkey" ON "category" ("id");
CREATE UNIQUE INDEX "coupons_code_unique" ON "coupons" ("code");
CREATE UNIQUE INDEX "coupons_pkey" ON "coupons" ("id");
CREATE UNIQUE INDEX "inventory_pkey" ON "inventory" ("product_id");
CREATE UNIQUE INDEX "order_coupons_pkey" ON "order_coupons" ("order_coupon_id");
CREATE INDEX "order_items_order_id_index" ON "order_items" ("order_id");
CREATE UNIQUE INDEX "order_items_pkey" ON "order_items" ("id");
CREATE INDEX "order_items_product_id_index" ON "order_items" ("product_id");
CREATE UNIQUE INDEX "payments_order_id_unique" ON "order_payments" ("order_id");
CREATE UNIQUE INDEX "payments_pkey" ON "order_payments" ("id");
CREATE UNIQUE INDEX "orders_pkey" ON "orders" ("id");
CREATE INDEX "orders_status_index" ON "orders" ("status");
CREATE INDEX "orders_user_id_index" ON "orders" ("user_id");
CREATE UNIQUE INDEX "payment_methods_code_key" ON "payment_methods" ("code");
CREATE UNIQUE INDEX "payment_methods_pkey" ON "payment_methods" ("id");
CREATE INDEX "product_category_id_index" ON "product" ("category_id");
CREATE UNIQUE INDEX "product_pkey" ON "product" ("id");
CREATE UNIQUE INDEX "product_slug_key" ON "product" ("slug");
CREATE UNIQUE INDEX "product_image_pkey" ON "product_image" ("id");
CREATE INDEX "product_image_product_id_index" ON "product_image" ("product_id");
CREATE UNIQUE INDEX "shipping_methods_code_key" ON "shipping_methods" ("code");
CREATE UNIQUE INDEX "shipping_methods_pkey" ON "shipping_methods" ("id");
CREATE UNIQUE INDEX "test_pkey" ON "test" ("id");
CREATE UNIQUE INDEX "users_email_unique" ON "users" ("email");
CREATE UNIQUE INDEX "users_pkey" ON "users" ("id");
ALTER TABLE "addresses" ADD CONSTRAINT "address_user_id_foreign" FOREIGN KEY ("user_id") REFERENCES "users"("id");
ALTER TABLE "cart_item" ADD CONSTRAINT "cart_item_product_id_foreign" FOREIGN KEY ("product_id") REFERENCES "product"("id") ON DELETE CASCADE;
ALTER TABLE "cart_item" ADD CONSTRAINT "cart_item_user_id_foreign" FOREIGN KEY ("user_id") REFERENCES "users"("id") ON DELETE CASCADE;
ALTER TABLE "inventory" ADD CONSTRAINT "inventory_product_id_foreign" FOREIGN KEY ("product_id") REFERENCES "product"("id");
ALTER TABLE "order_coupons" ADD CONSTRAINT "order_coupons_coupon_id_foreign" FOREIGN KEY ("coupon_id") REFERENCES "coupons"("id");
ALTER TABLE "order_coupons" ADD CONSTRAINT "order_coupons_order_id_foreign" FOREIGN KEY ("order_id") REFERENCES "orders"("id");
ALTER TABLE "order_items" ADD CONSTRAINT "order_items_order_id_foreign" FOREIGN KEY ("order_id") REFERENCES "orders"("id");
ALTER TABLE "order_items" ADD CONSTRAINT "order_items_product_id_foreign" FOREIGN KEY ("product_id") REFERENCES "product"("id");
ALTER TABLE "order_payments" ADD CONSTRAINT "payments_order_id_foreign" FOREIGN KEY ("order_id") REFERENCES "orders"("id");
ALTER TABLE "order_payments" ADD CONSTRAINT "payments_payment_method_foreign" FOREIGN KEY ("payment_method_id") REFERENCES "payment_methods"("id");
ALTER TABLE "orders" ADD CONSTRAINT "orders_address_id_foreign" FOREIGN KEY ("address_id") REFERENCES "addresses"("id");
ALTER TABLE "orders" ADD CONSTRAINT "orders_shipping_method_foreign" FOREIGN KEY ("shipping_method_id") REFERENCES "shipping_methods"("id");
ALTER TABLE "orders" ADD CONSTRAINT "orders_user_id_foreign" FOREIGN KEY ("user_id") REFERENCES "users"("id");
ALTER TABLE "product" ADD CONSTRAINT "product_category_id_foreign" FOREIGN KEY ("category_id") REFERENCES "category"("id");
ALTER TABLE "product_image" ADD CONSTRAINT "product_image_product_id_foreign" FOREIGN KEY ("product_id") REFERENCES "product"("id") ON DELETE CASCADE;