CREATE SCHEMA "public";
CREATE TABLE "address" (
	"id" uuid PRIMARY KEY DEFAULT uuid_generate_v4(),
	"user_id" uuid NOT NULL,
	"address_line" text NOT NULL,
	"city" varchar(100),
	"district" varchar(100),
	"ward" varchar(100),
	"is_default" boolean
);
CREATE TABLE "cart_item" (
	"id" uuid PRIMARY KEY DEFAULT uuid_generate_v4(),
	"user_id" uuid NOT NULL UNIQUE,
	"product_id" uuid NOT NULL UNIQUE,
	"quantity" integer NOT NULL,
	CONSTRAINT "cart_item_user_id_product_id_unique" UNIQUE("user_id","product_id")
);
CREATE TABLE "category" (
	"id" uuid PRIMARY KEY DEFAULT uuid_generate_v4(),
	"name" varchar(255) NOT NULL CONSTRAINT "category_name_key" UNIQUE,
	"created_at" timestamp DEFAULT CURRENT_TIMESTAMP
);
CREATE TABLE "coupon" (
	"id" uuid PRIMARY KEY DEFAULT uuid_generate_v4(),
	"code" varchar(50) NOT NULL CONSTRAINT "coupon_code_unique" UNIQUE,
	"discount_value" numeric(12, 2) NOT NULL,
	"expiry_date" timestamp,
	"min_order_value" numeric(12, 2),
	"max_discount" numeric(12, 2)
);
CREATE TABLE "inventory" (
	"product_id" uuid PRIMARY KEY,
	"quantity" integer NOT NULL
);
CREATE TABLE "order_coupon" (
	"order_coupon_id" uuid PRIMARY KEY DEFAULT uuid_generate_v4(),
	"order_id" uuid NOT NULL,
	"coupon_id" uuid NOT NULL
);
CREATE TABLE "order_item" (
	"id" uuid PRIMARY KEY DEFAULT uuid_generate_v4(),
	"order_id" uuid NOT NULL,
	"product_id" uuid NOT NULL,
	"quantity" integer NOT NULL,
	"price" numeric(12, 2) NOT NULL
);
CREATE TABLE "orders" (
	"id" uuid PRIMARY KEY DEFAULT uuid_generate_v4(),
	"user_id" uuid NOT NULL,
	"address_id" uuid NOT NULL,
	"subtotal" numeric(12, 2) NOT NULL,
	"discount" numeric(12, 2),
	"shipping_fee" numeric(12, 2),
	"final_price" numeric(12, 2) NOT NULL,
	"status" varchar(255) DEFAULT 'PENDING',
	"created_at" timestamp DEFAULT CURRENT_TIMESTAMP
);
CREATE TABLE "payment" (
	"id" uuid PRIMARY KEY DEFAULT uuid_generate_v4(),
	"order_id" uuid NOT NULL CONSTRAINT "payment_order_id_unique" UNIQUE,
	"method" integer NOT NULL,
	"status" varchar(255) DEFAULT 'PENDING',
	"paid_at" timestamp
);
CREATE TABLE "product" (
	"id" uuid PRIMARY KEY DEFAULT uuid_generate_v4(),
	"name" varchar(255) NOT NULL,
	"price" numeric(12, 2) NOT NULL,
	"description" text,
	"status" varchar(255) DEFAULT 'ACTIVE',
	"created_at" timestamp DEFAULT CURRENT_TIMESTAMP,
	"category_id" uuid,
	"slug" varchar(255) CONSTRAINT "product_slug_key" UNIQUE,
	"is_featured" boolean DEFAULT false
);
CREATE TABLE "product_image" (
	"id" uuid PRIMARY KEY DEFAULT uuid_generate_v4(),
	"product_id" uuid NOT NULL,
	"image_url" text NOT NULL,
	"sort_order" integer DEFAULT 0,
	"created_at" timestamp DEFAULT CURRENT_TIMESTAMP,
	"is_thumbnail" boolean DEFAULT false
);
CREATE TABLE "test" (
	"id" bigint PRIMARY KEY GENERATED BY DEFAULT AS IDENTITY (sequence name "test_id_seq" INCREMENT BY 1 MINVALUE 1 MAXVALUE 9223372036854775807 START WITH 1 CACHE 1),
	"name" varchar(255)
);
CREATE TABLE "users" (
	"id" uuid PRIMARY KEY DEFAULT uuid_generate_v4(),
	"email" varchar(255) NOT NULL CONSTRAINT "users_email_unique" UNIQUE,
	"hash_password" varchar(255) NOT NULL,
	"phone" varchar(20),
	"created_at" timestamp DEFAULT CURRENT_TIMESTAMP,
	"full_name" varchar(255)
);
CREATE UNIQUE INDEX "address_pkey" ON "address" ("id");
CREATE UNIQUE INDEX "cart_item_pkey" ON "cart_item" ("id");
CREATE INDEX "cart_item_product_id_index" ON "cart_item" ("product_id");
CREATE INDEX "cart_item_user_id_index" ON "cart_item" ("user_id");
CREATE UNIQUE INDEX "cart_item_user_id_product_id_unique" ON "cart_item" ("user_id","product_id");
CREATE UNIQUE INDEX "category_name_key" ON "category" ("name");
CREATE UNIQUE INDEX "category_pkey" ON "category" ("id");
CREATE UNIQUE INDEX "coupon_code_unique" ON "coupon" ("code");
CREATE UNIQUE INDEX "coupon_pkey" ON "coupon" ("id");
CREATE UNIQUE INDEX "inventory_pkey" ON "inventory" ("product_id");
CREATE UNIQUE INDEX "order_coupon_pkey" ON "order_coupon" ("order_coupon_id");
CREATE INDEX "order_item_order_id_index" ON "order_item" ("order_id");
CREATE UNIQUE INDEX "order_item_pkey" ON "order_item" ("id");
CREATE INDEX "order_item_product_id_index" ON "order_item" ("product_id");
CREATE UNIQUE INDEX "orders_pkey" ON "orders" ("id");
CREATE INDEX "orders_status_index" ON "orders" ("status");
CREATE INDEX "orders_user_id_index" ON "orders" ("user_id");
CREATE UNIQUE INDEX "payment_order_id_unique" ON "payment" ("order_id");
CREATE UNIQUE INDEX "payment_pkey" ON "payment" ("id");
CREATE INDEX "product_category_id_index" ON "product" ("category_id");
CREATE UNIQUE INDEX "product_pkey" ON "product" ("id");
CREATE UNIQUE INDEX "product_slug_key" ON "product" ("slug");
CREATE UNIQUE INDEX "product_image_pkey" ON "product_image" ("id");
CREATE INDEX "product_image_product_id_index" ON "product_image" ("product_id");
CREATE UNIQUE INDEX "test_pkey" ON "test" ("id");
CREATE UNIQUE INDEX "users_email_unique" ON "users" ("email");
CREATE UNIQUE INDEX "users_pkey" ON "users" ("id");
ALTER TABLE "address" ADD CONSTRAINT "address_user_id_foreign" FOREIGN KEY ("user_id") REFERENCES "users"("id");
ALTER TABLE "cart_item" ADD CONSTRAINT "cart_item_product_id_foreign" FOREIGN KEY ("product_id") REFERENCES "product"("id");
ALTER TABLE "cart_item" ADD CONSTRAINT "cart_item_user_id_foreign" FOREIGN KEY ("user_id") REFERENCES "users"("id");
ALTER TABLE "inventory" ADD CONSTRAINT "inventory_product_id_foreign" FOREIGN KEY ("product_id") REFERENCES "product"("id");
ALTER TABLE "order_coupon" ADD CONSTRAINT "order_coupon_coupon_id_foreign" FOREIGN KEY ("coupon_id") REFERENCES "coupon"("id");
ALTER TABLE "order_coupon" ADD CONSTRAINT "order_coupon_order_id_foreign" FOREIGN KEY ("order_id") REFERENCES "orders"("id");
ALTER TABLE "order_item" ADD CONSTRAINT "order_item_order_id_foreign" FOREIGN KEY ("order_id") REFERENCES "orders"("id");
ALTER TABLE "order_item" ADD CONSTRAINT "order_item_product_id_foreign" FOREIGN KEY ("product_id") REFERENCES "product"("id");
ALTER TABLE "orders" ADD CONSTRAINT "orders_address_id_foreign" FOREIGN KEY ("address_id") REFERENCES "address"("id");
ALTER TABLE "orders" ADD CONSTRAINT "orders_user_id_foreign" FOREIGN KEY ("user_id") REFERENCES "users"("id");
ALTER TABLE "payment" ADD CONSTRAINT "payment_order_id_foreign" FOREIGN KEY ("order_id") REFERENCES "orders"("id");
ALTER TABLE "product" ADD CONSTRAINT "product_category_id_foreign" FOREIGN KEY ("category_id") REFERENCES "category"("id");
ALTER TABLE "product_image" ADD CONSTRAINT "product_image_product_id_foreign" FOREIGN KEY ("product_id") REFERENCES "product"("id") ON DELETE CASCADE;
